### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by arvati** [d235j/lenovoEMC-300d#1]
Could be possible to provide some instructions on how to use or compile these drivers for lenovoEMC px4-300d ?

**Comment by d235j** [comment]
These are set up to compile out of tree; they are experimental though and I'm no longer using the hardware so it is unlikely much more will happen with them.
The turn-of-lights.sh script compiles some of them.

**Comment by d235j** [comment]
@arvati if I may ask what is your interest in these?

**Comment by arvati** [comment]
D235j

I would like to install Openwrt on it and include these drivers on my
custom image.

Does it need to compile together with kernel sources inside some special
folder or just issue make like your example?

Br
Arvati

Em 28 de ago de 2018 9:50 PM, "David Ryskalczyk" <notifications@github.com>
escreveu:

@arvati <https://github.com/arvati> if I may ask what is your interest in
these?

**Comment by d235j** [comment]
@arvati I was running standard Arch Linux, loosely following these instructions
https://open-desk.org/?p=276

The Lenovo px-300d hardware is mostly a plain Intel Atom box, so this is not too difficult.
These kernel modules are by no means required; they are derived from the Lenovo GPL releases that can be found here: http://download.lenovo.com/lenovoemc/na/en/
This site is rather broken because it was moved from the Oracle Customer Experience (CX) Service.
The source code archive at http://download.lenovo.com/lenovoemc/na/en/app/answers/detail/a_id/34437.html is broken (truncated).
The older archive at http://download.lenovo.com/nas/foss/lenovoemc-lifeline-fosskit-4.1.212.33882.tar.gz seems to work, though. The kernel module source for the custom modules is in Lifeline_FossKit/linux/patch. The modules in this repo are partly derived from those.

I was using them to disable the front panel display and bright lights, but with some work they could be made more useful.

**Comment by d235j** [comment]
@arvati I followed up with Lenovo and they finally fixed the newest Fosskit download. It is at
http://download.lenovo.com/nas/foss/lenovoemc-lifeline-fosskit-4.1.312.34560.tar.gz

**Comment by d235j** [comment]
Also the drivers that are here are set up for out of tree compile.

**Comment by arvati** [comment]
Thank you very much i will check those fosskit files before working on these drivers.

files from version: 4.1.312.34560
http://download.lenovo.com/nas/lifeline/px4px6-4.1.312.34560.tgz
https://download.lenovo.com/nasupdate/asgimage/px4px6-4.1.312.34560.zip
http://download.lenovo.com/nas/foss/lenovoemc-lifeline-fosskit-4.1.312.34560.tar.gz

files from version: 4.1.402.34662
https://download.lenovo.com/nasupdate/asgimage/px4px6-4.1.402.34662.zip
http://download.lenovo.com/nas/lifeline/px4px6-4.1.402.34662.tgz
http://download.lenovo.com/nas/foss/lenovoemc-lifeline-fosskit-4.1.402.34662.tar.gz

files from version: 4.1.404.34716
https://download.lenovo.com/nasupdate/asgimage/px4px6-4.1.404.34716.zip
http://download.lenovo.com/nas/lifeline/px4px6-4.1.404.34716.tgz
